import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { clientAuth } from "@/auth-client";
import { auth } from "@/auth";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

export const runtime = "nodejs";

type Params = { params: Promise<{ id: string }> };

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: { marginBottom: 24 },
  title: { fontSize: 22, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#666" },
  meta: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  metaBlock: { flex: 1 },
  metaLabel: { fontSize: 8, color: "#999", marginBottom: 2 },
  metaValue: { fontSize: 10 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 11, fontWeight: "bold", marginBottom: 8, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: "#ddd" },
  headerRow: { flexDirection: "row", paddingVertical: 6, borderBottomWidth: 2, borderBottomColor: "#333", fontWeight: "bold" },
  row: { flexDirection: "row", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#eee" },
  col1: { flex: 4 },
  col2: { flex: 1, textAlign: "right" },
  totalRow: { flexDirection: "row", paddingTop: 10, marginTop: 4 },
  totalLabel: { flex: 5, textAlign: "right", fontWeight: "bold", fontSize: 12 },
  totalValue: { flex: 1, textAlign: "right", fontWeight: "bold", fontSize: 12 },
  paidNote: { fontSize: 10, fontWeight: "bold", marginTop: 10, color: "#16a34a" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#999" },
});

function InvoiceDocument({ invoice, lineItems }: { invoice: any; lineItems: any[] }) {
  const fmt = (cents: number) =>
    new Intl.NumberFormat("en-US", { style: "currency", currency: invoice.currency }).format(cents / 100);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>INVOICE</Text>
          <Text style={styles.subtitle}>{invoice.number}</Text>
        </View>

        <View style={styles.meta}>
          <View style={styles.metaBlock}>
            <Text style={styles.metaLabel}>BILL TO</Text>
            <Text style={styles.metaValue}>{invoice.client.name || invoice.client.email}</Text>
            {invoice.client.company ? <Text style={styles.metaValue}>{invoice.client.company}</Text> : null}
            <Text style={styles.metaValue}>{invoice.client.email}</Text>
          </View>
          <View style={styles.metaBlock}>
            <Text style={styles.metaLabel}>DATE</Text>
            <Text style={styles.metaValue}>{new Date(invoice.createdAt).toISOString().slice(0, 10)}</Text>
            {invoice.dueDate ? (
              <View>
                <Text style={{ ...styles.metaLabel, marginTop: 8 }}>DUE DATE</Text>
                <Text style={styles.metaValue}>{new Date(invoice.dueDate).toISOString().slice(0, 10)}</Text>
              </View>
            ) : null}
          </View>
          <View style={styles.metaBlock}>
            <Text style={styles.metaLabel}>STATUS</Text>
            <Text style={styles.metaValue}>{invoice.status.toUpperCase()}</Text>
            {invoice.project ? (
              <View>
                <Text style={{ ...styles.metaLabel, marginTop: 8 }}>PROJECT</Text>
                <Text style={styles.metaValue}>{invoice.project.title}</Text>
              </View>
            ) : null}
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Items</Text>
          <View style={styles.headerRow}>
            <Text style={styles.col1}>Description</Text>
            <Text style={styles.col2}>Amount</Text>
          </View>
          {lineItems.map((item, i) => (
            <View style={styles.row} key={i}>
              <Text style={styles.col1}>{item.description || ""}</Text>
              <Text style={styles.col2}>{fmt(item.amount)}</Text>
            </View>
          ))}
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>TOTAL:</Text>
            <Text style={styles.totalValue}>{fmt(invoice.amount)}</Text>
          </View>
        </View>

        {invoice.paidAt ? (
          <View style={styles.section}>
            <Text style={styles.paidNote}>PAID on {new Date(invoice.paidAt).toISOString().slice(0, 10)}</Text>
            {invoice.paymentRef ? <Text style={styles.subtitle}>Ref: {invoice.paymentRef}</Text> : null}
          </View>
        ) : null}

        <Text style={styles.footer}>Generated by CiroStack</Text>
      </Page>
    </Document>
  );
}

export async function GET(_req: Request, { params }: Params) {
  const { id } = await params;

  const clientSession = await clientAuth();
  const adminSession = await auth();
  const clientId = clientSession?.user ? (clientSession.user as any).id : null;

  try {
    const invoice = await prisma.invoice.findFirst({
      where: { id, ...(adminSession?.user ? {} : { clientId }) },
      include: { client: true, project: { select: { title: true } } },
    });
    if (!invoice) return NextResponse.json({ error: "Not found" }, { status: 404 });

    type RawItem = { description: string; qty?: number; unitPrice?: number; amount?: number };
    const lineItems = (invoice.lineItems as RawItem[]).map((l) => ({
      description: l.description,
      amount: l.amount !== undefined ? l.amount : (l.qty ?? 1) * (l.unitPrice ?? 0),
    }));

    const pdfBuffer = await renderToBuffer(<InvoiceDocument invoice={invoice} lineItems={lineItems} />);

    return new NextResponse(new Uint8Array(pdfBuffer), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="invoice-${invoice.number}.pdf"`,
      },
    });
  } catch (err: any) {
    console.error("[GET /api/portal/invoices/[id]/pdf]", err);
    return NextResponse.json({ error: "Failed to generate PDF", detail: err?.message }, { status: 500 });
  }
}
