import re
import sys

NEW_DESCRIPTIONS = {
    # ===================== RETAIL & E-COMMERCE =====================
    "online-retail-stores": "CiroStack engineers headless commerce platforms that separate your storefront from your backend, delivering pixel perfect creative control, real time inventory accuracy across every sales channel, and the elimination of costly platform transaction fees eroding your margins.",
    "brick-and-mortar-retail": "Physical retail is being outpaced by data. CiroStack builds the technology layer that closes this gap with unified POS systems, mobile clienteling apps, and sensor based analytics that map foot traffic patterns and conversion funnels through your space.",
    "fashion-and-apparel": "One in three online apparel purchases gets returned because customers cannot assess fit through a screen. CiroStack builds AI size recommendation engines, AR virtual try on tools, and smart product pages that eliminate the guesswork causing returns.",
    "grocery-and-food-delivery": "Grocery commerce operates on thin margins with perishable inventory, complex substitution logic, and delivery windows measured in hours. CiroStack builds custom platforms handling real time stock management, route optimized dispatch, and intelligent substitution engines for every order.",
    "electronics-and-gadgets": "Selling electronics online demands more than a product catalog. Customers compare specs across brands and worry about compatibility. CiroStack builds product comparison engines, spec driven search filters, and compatibility verification tools that drive confident purchase decisions.",
    "furniture-and-home-decor": "Furniture is the hardest ecommerce category because products are too large to imagine and too expensive to gamble on. CiroStack builds AR room visualization tools, product configurators, and delivery scheduling systems that reduce returns and increase buyer confidence.",
    "beauty-and-cosmetics": "Beauty ecommerce faces a fundamental trust gap since customers cannot swatch shades or test products through a screen. CiroStack builds virtual shade matching tools, ingredient analysis platforms, and skin profile engines that personalize every shopping experience.",
    "bookstores": "Bookstores cannot compete with major retailers on price or selection, but they can win on discovery and community. CiroStack builds recommendation engines, community reading platforms, event management systems, and curated discovery experiences that transform browsing into loyalty.",
    "pharmacies": "Pharmacy technology is stuck between outdated legacy systems and consumer apps that prioritize plan profitability over patient care. CiroStack builds modern prescription management platforms, medication adherence tools, and HIPAA compliant patient communication systems that actually serve pharmacists.",
    "automotive-parts": "Every automotive part has a critical compatibility constraint tied to specific vehicle years, makes, models, and engine configurations. CiroStack builds commerce platforms with VIN based fitment verification, interchange databases, and B2B ordering portals for accurate fulfillment.",

    # ===================== HEALTHCARE & MEDICAL =====================
    "hospitals-and-clinics": "Hospitals and clinics face mounting pressure to reduce wait times, improve outcomes, streamline insurance processing, and meet strict privacy regulations. CiroStack builds custom digital platforms that unify patient scheduling, clinical workflows, billing, and compliance into one system.",
    "telemedicine": "Patients expect virtual visits that feel as seamless as in person appointments. CiroStack builds custom telemedicine platforms that integrate secure video consultations, electronic prescriptions, and clinical records directly into your existing practice management workflow without disruption.",
    "dental-practices": "Running a dental practice means balancing clinical care with business operations. CiroStack builds digital tools that keep appointment books full, automate insurance verification, streamline treatment plan acceptance, and create patient communication systems that drive retention and referrals.",
    "mental-health": "Mental health care is deeply personal, and supporting technology should remain invisible to the therapeutic process. CiroStack builds platforms that handle scheduling, insurance billing, session documentation, and secure client communication so therapists can focus entirely on patient care.",
    "pharmacies-medical": "Modern pharmacies must handle online refill ordering, medication reminders, immunization scheduling, and personalized health advice alongside traditional dispensing. CiroStack builds integrated pharmacy platforms that automate prescription processing, ensure regulatory compliance, and strengthen patient relationships at every touchpoint.",
    "fitness-and-wellness": "The fitness and wellness industry runs on relationships and habits. Your members need reasons to keep returning, and your staff needs tools that stay out of the way. CiroStack builds member engagement platforms, class scheduling systems, and retention analytics.",
    "medical-equipment": "Selling and servicing medical equipment requires detailed specifications, compliance documentation, and responsive support across long sales cycles. CiroStack builds custom platforms that simplify complex product catalogs, automate regulatory paperwork, and streamline the entire equipment sales lifecycle.",
    "laboratories": "Whether you operate a clinical diagnostic lab or research facility, your daily work depends on precision and speed. CiroStack builds custom LIMS integrations, sample tracking systems, and automated reporting platforms that eliminate manual bottlenecks and accelerate result delivery.",
    "physical-therapy": "The biggest challenge in physical therapy is operational, not clinical. Patients drop out early, documentation consumes hours, and insurance authorizations expire silently. CiroStack builds engagement tools, automated documentation systems, and authorization tracking that keep patients completing their care.",
    "senior-care": "Senior care facilities manage clinical care, daily operations, regulatory compliance, staffing, and family communication simultaneously. CiroStack builds unified platforms that coordinate care teams, automate compliance documentation, keep families informed, and give administrators real time visibility across every facility.",

    # ===================== FINANCIAL SERVICES =====================
    "banks-and-credit-unions": "Whether you are a community bank or credit union, your digital experience is now your biggest differentiator. CiroStack builds custom banking platforms with modern interfaces, mobile apps, and secure integrations that keep members loyal and operations efficient.",
    "investment-firms": "Investment firms depend on decision quality and client trust. CiroStack builds platforms that unify portfolio data, market intelligence, and client communications into a single system, giving advisors instant insights and investors a transparent, professional digital experience.",
    "insurance": "Policyholders now expect instant quotes, mobile claims filing, and real time status tracking. CiroStack builds custom insurance platforms that automate underwriting workflows, accelerate claims processing, and deliver the seamless digital experiences your customers receive in every other industry.",
    "fintech-startups": "Fintech moves fast, but financial regulations demand precision. CiroStack helps startups build products that are both innovative and compliant from day one so you are not retrofitting security and regulatory controls after your product is already in market.",
    "accounting-firms": "Accounting firms are burdened by client documents, manual data entry, and disconnected tools. CiroStack builds integrated platforms that automate repetitive workflows, provide clients with modern self service portals, and free your team to focus on advisory work.",
    "personal-finance": "Most personal finance products feel like they were designed by engineers, not for real people. CiroStack builds consumer facing financial tools that are beautiful, intuitive, and focused on helping users build lasting habits around saving, budgeting, and investing.",
    "cryptocurrency": "Whether you are building an exchange, a wallet, or a DeFi interface, the challenge remains the same. CiroStack builds crypto platforms that combine institutional grade security with consumer friendly experiences that make blockchain technology accessible to everyday users.",
    "microfinance": "Microfinance institutions change lives, but outdated technology limits how many communities you can reach. CiroStack builds platforms that streamline loan origination, automate repayment tracking, ensure regulatory compliance, and scale your social impact without proportionally scaling your operational overhead.",
    "real-estate-investment": "Whether you run a REIT, manage a private equity fund, or syndicate individual deals, technology gaps cost you opportunities. CiroStack builds platforms for instant deal analysis, real time portfolio monitoring, and automated investor reporting across your entire operation.",
    "credit-unions": "Credit unions face a unique challenge competing with banks and fintechs on technology while staying true to a member owned mission. CiroStack builds platforms that deliver modern digital banking experiences while reinforcing the community focused values your members trust.",

    # ===================== REAL ESTATE & PROPERTY =====================
    "real-estate-agencies": "Real estate agencies juggle listings, client relationships, and transaction management across multiple platforms. CiroStack builds unified agency platforms with intelligent CRM systems, automated listing syndication, client portals, and transaction tracking that close deals faster and delight clients.",
    "property-management": "Property management companies handle tenant communications, maintenance requests, rent collection, and lease renewals across dozens or hundreds of units. CiroStack builds custom tenant portals, automated maintenance dispatch, financial reporting dashboards, and lease management tools for efficient operations.",
    "real-estate-investment-prop": "Real estate investors need instant visibility into deal performance, portfolio health, and market opportunities. CiroStack builds custom investment platforms with automated deal analysis, portfolio tracking dashboards, investor reporting portals, and market intelligence tools that accelerate better decisions.",
    "commercial-real-estate": "Commercial real estate operates on complex lease structures, tenant improvement negotiations, and long sales cycles. CiroStack builds custom platforms for lease management, tenant relationship tracking, property analytics, and deal pipeline management that streamline every commercial transaction.",
    "vacation-rentals": "Vacation rental operators manage bookings across multiple channels while delivering memorable guest experiences. CiroStack builds custom booking engines, channel management systems, automated guest communication tools, and dynamic pricing platforms that maximize occupancy and revenue year round.",
    "property-development": "Property development projects demand precise coordination of budgets, timelines, contractors, and stakeholder expectations. CiroStack builds custom project management platforms, budget tracking dashboards, contractor portals, and stakeholder reporting tools that keep complex developments on schedule and within budget.",
    "real-estate-agents": "Real estate agents need technology that works as fast as they do. CiroStack builds custom CRM platforms, automated lead nurturing systems, listing management tools, and client communication portals that help agents close more deals while spending less time on administration.",
    "mortgage-brokers": "Mortgage brokers navigate complex loan products, compliance requirements, and time sensitive client expectations. CiroStack builds custom loan processing platforms, rate comparison engines, document management systems, and compliance tracking tools that accelerate closings and improve borrower satisfaction.",
    "facility-management": "Facility managers oversee building operations, maintenance schedules, vendor relationships, and space utilization across multiple properties. CiroStack builds custom work order systems, preventive maintenance platforms, space optimization tools, and vendor management portals for streamlined facility operations.",
    "co-working-spaces": "Coworking spaces balance membership management, room bookings, community engagement, and space utilization. CiroStack builds custom member portals, booking systems, community platforms, and occupancy analytics dashboards that create thriving workspace communities while maximizing revenue per square foot.",

    # ===================== EDUCATION & E-LEARNING =====================
    "schools-and-universities": "Most educational institutions run on a patchwork of disconnected systems for admissions, academics, and administration. CiroStack builds unified platforms that connect student information systems, learning management, parent portals, and reporting into one seamless digital experience.",
    "online-courses": "Generic course platforms cap your growth with transaction fees, limited customization, and poor video delivery. CiroStack builds custom learning platforms with integrated payment processing, adaptive content delivery, and student progress tracking that scale with your growing audience.",
    "corporate-training": "Standard learning management systems are built for average companies, not your specific compliance workflows or skills requirements. CiroStack builds custom corporate training platforms with completion tracking, compliance automation, skills gap analysis, and reporting dashboards tailored to your organization.",
    "tutoring-services": "Most tutoring businesses run on a patchwork of scheduling, payment, and communication tools that were never designed to work together. CiroStack builds unified tutoring platforms with integrated scheduling, progress tracking, automated billing, and parent communication in one system.",
    "test-preparation": "Generic quiz apps do not move standardized test scores. CiroStack builds custom test prep platforms with adaptive practice engines that target each student's weakest areas, predictive score analytics, and personalized study plans that turn every practice hour into measurable improvement.",
    "language-learning": "Most language apps lose learners within two weeks because they lack the engagement to sustain long term study. CiroStack builds custom platforms with spaced repetition engines, AI conversation practice, speech analysis, and gamified progress systems that keep learners committed.",
    "childcare": "Childcare centers manage enrollment, daily reports, parent communication, and regulatory compliance with limited technology. CiroStack builds custom platforms that automate attendance tracking, streamline parent updates, simplify billing, and ensure licensing compliance so caregivers can focus on children.",
    "vocational-training": "Vocational training programs must bridge classroom instruction with hands on skill development and industry certification. CiroStack builds custom learning platforms with competency tracking, practical assessment tools, certification management, and employer connection portals that prepare students for immediate employment.",
    "educational-publishers": "Educational publishers face the digital transformation of content delivery, assessment, and student engagement. CiroStack builds custom digital publishing platforms with interactive content tools, adaptive learning features, analytics dashboards, and institutional licensing systems that modernize how educational content reaches learners.",
    "coding-bootcamps": "Coding bootcamps must deliver intensive technical curricula while tracking student progress and employment outcomes. CiroStack builds custom learning platforms with integrated coding environments, project based assessment tools, career services portals, and outcome tracking dashboards that drive student success.",

    # ===================== HOSPITALITY & TOURISM =====================
    "hotels-and-resorts": "Hotels and resorts compete on guest experience from booking through checkout. CiroStack builds custom hospitality platforms with direct booking engines, guest experience apps, operations management systems, and loyalty programs that increase direct revenue and guest satisfaction.",
    "restaurants-and-cafes": "Restaurants and cafes balance front of house service, kitchen operations, and customer loyalty across every shift. CiroStack builds custom POS integrations, online ordering platforms, kitchen display systems, and loyalty programs that streamline operations and keep customers returning.",
    "travel-agencies": "Travel agencies must curate personalized experiences while managing supplier relationships and complex itineraries. CiroStack builds custom booking platforms, itinerary management tools, CRM systems, and supplier integration portals that let agents focus on creating unforgettable travel experiences.",
    "airlines": "Airlines operate complex reservation systems, fleet management, and loyalty programs across millions of passengers. CiroStack builds custom booking platforms, operational dashboards, crew scheduling tools, and passenger experience applications that improve efficiency and strengthen customer loyalty.",
    "tour-operators": "Tour operators coordinate guides, transportation, accommodations, and activities across multiple destinations and seasons. CiroStack builds custom booking engines, inventory management systems, guide scheduling tools, and customer experience platforms that simplify operations while scaling your tour business.",
    "event-venues": "Event venues manage bookings, client requirements, vendor coordination, and floor plans for hundreds of events yearly. CiroStack builds custom venue management platforms with booking calendars, client portals, vendor coordination tools, and event planning dashboards that maximize venue utilization.",
    "bed-and-breakfasts": "Bed and breakfasts rely on personal touches and direct relationships that large hotel chains cannot replicate. CiroStack builds custom direct booking engines, guest communication tools, property management systems, and review management platforms that reduce OTA dependency and protect margins.",
    "cruise-lines": "Cruise lines manage onboard experiences, shore excursions, dining, and entertainment for thousands of guests simultaneously. CiroStack builds custom guest experience platforms, excursion booking systems, onboard service apps, and operations dashboards that elevate every moment of the voyage.",
    "car-rentals": "Car rental companies manage fleet availability, pricing, maintenance, and customer reservations across multiple locations. CiroStack builds custom fleet management platforms, dynamic pricing engines, online reservation systems, and vehicle tracking tools that maximize fleet utilization and revenue.",
    "travel-bloggers": "Travel bloggers and content creators need platforms that showcase their journeys while monetizing their audience effectively. CiroStack builds custom content management systems, affiliate integration tools, audience analytics dashboards, and sponsorship management platforms that turn travel stories into sustainable businesses.",

    # ===================== MANUFACTURING & INDUSTRIAL =====================
    "manufacturing-plants": "Most manufacturers operate with stale ERP data, manual downtime reports, and spreadsheet based production scheduling. CiroStack builds custom MES platforms, real time OEE dashboards, and production scheduling systems that give shift supervisors instant visibility across every line.",
    "supply-chain-and-logistics": "Supply chain teams manage enormous complexity with surprisingly primitive tools. CiroStack builds demand forecasting engines, supplier management portals, and EDI integration middleware that replace spreadsheet driven planning with systems providing real time visibility across your entire supply network.",
    "warehousing": "Warehouse operations depend on speed and accuracy, yet most facilities undermine both with outdated systems. CiroStack builds custom WMS platforms, pick and pack workflow systems, and labor management dashboards that eliminate mispicks, reduce shrinkage, and accelerate fulfillment throughput.",
    "quality-control": "Quality problems are information problems. Process drift and out of spec materials cause defects long before inspectors discover them. CiroStack builds statistical process control systems, digital inspection workflows, and defect tracking platforms that catch quality issues at the source.",
    "equipment-maintenance": "Most maintenance teams operate in managed chaos with spreadsheet work orders and calendar based schedules. CiroStack builds custom CMMS platforms, predictive maintenance dashboards, and spare parts inventory systems that shift your strategy from reactive firefighting to precision prevention.",
    "factory-automation": "Factory automation generates enormous data that most manufacturers never fully use. CiroStack builds PLC integration layers, custom SCADA dashboards, and IoT sensor platforms that transform raw machine data into actionable production intelligence visible across every level of your organization.",
    "procurement": "Procurement inefficiency is expensive and largely invisible when purchase orders take days to route through email approvals. CiroStack builds custom procurement platforms, vendor management portals, and spend analytics systems that automate approval workflows and deliver complete spending visibility.",
    "distribution": "Distribution operations live and die by cost per delivery and on time performance. CiroStack builds route optimization engines, order management systems, and warehouse to delivery tracking platforms that reduce delivery costs, improve schedule reliability, and give customers real time visibility.",
    "chemical-and-pharmaceutical": "Chemical and pharmaceutical manufacturing operates under compliance burdens that generic software cannot address. CiroStack builds batch management systems, LIMS integrations, and regulatory documentation platforms that maintain full traceability from raw material receipt through finished product release.",
    "automotive-manufacturing": "Automotive manufacturing demands supply chain precision that most industries never face, with exact sequence delivery to assembly lines. CiroStack builds JIT inventory management systems, supplier scorecard platforms, and part traceability solutions that meet the exacting standards of OEM customers.",

    # ===================== PROFESSIONAL SERVICES =====================
    "law-firms": "Most law firms run on disconnected tools where case files, billing, communications, and documents live in separate systems. CiroStack builds unified practice management platforms that automate document assembly, streamline case workflows, and give clients a modern digital experience.",
    "accounting-firms-pro": "Accounting firms spend tax season buried in manual data extraction, client document collection, and system reconciliation. CiroStack builds custom practice management platforms, automated tax workflow engines, client portals, and analytics dashboards that eliminate the administrative overhead consuming your billable hours.",
    "consulting-agencies": "Consulting firms struggle with project tracking, utilization management, and client delivery across distributed teams. CiroStack builds custom project management platforms, resource allocation tools, client collaboration portals, and performance analytics dashboards that improve utilization rates and client satisfaction simultaneously.",
    "marketing-agencies": "Marketing agencies juggle creative projects, client approvals, campaign analytics, and team utilization across multiple accounts simultaneously. CiroStack builds custom project management platforms, creative workflow tools, client reporting dashboards, and resource planning systems that keep every campaign on track.",
    "architecture-firms": "Architecture firms coordinate complex design projects spanning BIM workflows, client reviews, regulatory submissions, and construction documentation. CiroStack builds custom project management platforms, BIM collaboration tools, client review portals, and document management systems that streamline every design phase.",
    "engineering-firms": "Engineering firms manage technical projects requiring precise documentation, regulatory compliance, and cross discipline collaboration. CiroStack builds custom project tracking platforms, technical document management systems, compliance workflow tools, and client reporting dashboards that keep complex engineering projects organized.",
    "hr-consulting": "HR consulting firms handle sensitive employee data, compliance requirements, and organizational change across multiple client engagements. CiroStack builds custom client management platforms, compliance tracking tools, assessment delivery systems, and engagement analytics dashboards that scale your advisory capacity.",
    "it-services": "IT service providers manage support tickets, service level agreements, and infrastructure monitoring across diverse client environments. CiroStack builds custom ticketing platforms, SLA tracking dashboards, remote monitoring tools, and client portals that improve response times and demonstrate measurable value.",
    "recruiting-agencies": "Recruiting agencies track candidates, client requirements, and placements across dozens of simultaneous searches. CiroStack builds custom applicant tracking systems, candidate pipeline dashboards, client portals, and placement management tools that help recruiters fill positions faster with stronger matches.",
    "business-coaching": "Business coaches manage client relationships, session scheduling, progress tracking, and content delivery across growing practices. CiroStack builds custom coaching platforms with client management tools, goal tracking dashboards, session scheduling systems, and resource libraries that scale your impact.",

    # ===================== MEDIA & ENTERTAINMENT =====================
    "film-and-video-production": "Film and video productions coordinate talent, equipment, locations, and post production workflows across tight timelines and budgets. CiroStack builds custom production management platforms, asset tracking systems, scheduling tools, and collaboration portals that keep productions running on schedule.",
    "music-industry": "Musicians and labels manage royalty splits, distribution across streaming platforms, and fan engagement while navigating complex licensing agreements. CiroStack builds custom royalty tracking systems, distribution management platforms, fan engagement tools, and catalog administration portals for the modern music business.",
    "gaming": "Game studios need infrastructure that handles millions of concurrent players, real time matchmaking, and live service updates without downtime. CiroStack builds custom game backend systems, player analytics platforms, matchmaking engines, and live operations dashboards that keep players engaged.",
    "photography": "Professional photographers spend enormous time on work that technology should handle, from sending contracts to delivering galleries. CiroStack builds unified photography business platforms that manage the complete client lifecycle from inquiry and booking through gallery delivery and reordering.",
    "publishing": "Publishers navigate the shift from print to digital while managing editorial workflows, distribution channels, and audience engagement. CiroStack builds custom editorial management systems, digital distribution platforms, subscription engines, and audience analytics tools that modernize publishing operations.",
    "news-and-media": "News organizations must publish faster, engage audiences deeper, and monetize content more effectively across every digital channel. CiroStack builds custom content management systems, audience analytics platforms, subscription engines, and advertising management tools that sustain independent journalism.",
    "podcasting": "Podcasters need more than a hosting platform. They need tools for production, distribution, audience growth, and monetization that work together seamlessly. CiroStack builds custom podcast management platforms, distribution tools, analytics dashboards, and sponsorship management systems for growing shows.",
    "event-production": "Event production companies coordinate vendors, technical crews, timelines, and client expectations across multiple simultaneous productions. CiroStack builds custom event management platforms, vendor coordination tools, production scheduling systems, and client communication portals that ensure flawless event execution.",
    "social-media-influencers": "Influencers and creators manage content calendars, brand partnerships, audience analytics, and revenue streams across multiple platforms. CiroStack builds custom creator management platforms, brand deal tracking tools, content scheduling systems, and performance analytics dashboards that maximize creator earning potential.",
    "art-galleries": "Art galleries balance exhibition planning, artist relationships, inventory management, and collector engagement across physical and digital spaces. CiroStack builds custom gallery management platforms, inventory tracking systems, collector CRM tools, and online exhibition portals that expand audience reach.",

    # ===================== NON-PROFIT & SOCIAL ENTERPRISE =====================
    "charities": "Charities depend on donor relationships, fundraising campaigns, and transparent impact reporting to sustain their mission. CiroStack builds custom donor management platforms, fundraising tools, volunteer coordination systems, and impact dashboards that help charitable organizations grow their reach and trust.",
    "ngos": "NGOs operate complex programs across multiple regions while managing donor requirements and measuring outcomes. CiroStack builds custom program management platforms, field operations tools, donor reporting systems, and impact measurement dashboards that help organizations scale their mission without scaling overhead.",
    "religious-organizations": "Religious organizations serve communities through worship, outreach, education, and support programs that require careful coordination. CiroStack builds custom community management platforms, event scheduling tools, giving management systems, and member communication portals that strengthen congregation engagement and participation.",
    "community-groups": "Community groups bring people together around shared interests, causes, and local initiatives. CiroStack builds custom member management platforms, event coordination tools, communication systems, and resource sharing portals that help community organizations grow engagement and amplify collective impact.",
    "foundations": "Foundations manage grant cycles, evaluate proposals, track disbursements, and measure the impact of funded programs. CiroStack builds custom grant management platforms, application review tools, disbursement tracking systems, and outcomes reporting dashboards that streamline philanthropy and maximize every dollar.",
    "social-enterprises": "Social enterprises balance mission driven impact with sustainable business operations. CiroStack builds custom platforms that integrate commerce, impact tracking, and stakeholder reporting into unified systems so organizations can grow revenue while measuring and communicating the social outcomes that define success.",
    "environmental-groups": "Environmental organizations coordinate conservation efforts, advocacy campaigns, and scientific research across vast geographies. CiroStack builds custom campaign management platforms, field data collection tools, donor engagement systems, and environmental monitoring dashboards that amplify conservation impact and supporter involvement.",
    "educational-non-profits": "Educational nonprofits deliver learning programs to underserved communities while tracking outcomes for donors and stakeholders. CiroStack builds custom program delivery platforms, student progress tracking tools, volunteer management systems, and impact reporting dashboards that demonstrate measurable educational outcomes.",
    "health-advocacy": "Health advocacy organizations raise awareness, support patients, and drive policy change around critical health issues. CiroStack builds custom campaign management platforms, patient support portals, research tracking tools, and community engagement systems that amplify health advocacy missions and connect stakeholders.",
    "animal-welfare": "Animal welfare organizations manage rescue operations, adoption processes, foster networks, and donor relationships while caring for animals in need. CiroStack builds custom shelter management platforms, adoption portals, foster coordination tools, and fundraising systems that save more lives.",

    # ===================== TECHNOLOGY & STARTUPS =====================
    "saas-companies": "SaaS companies need infrastructure that scales with customer growth while maintaining the reliability and security enterprise buyers demand. CiroStack builds custom billing systems, multi tenant architectures, API platforms, and admin dashboards that let product teams ship features faster.",
    "tech-startups": "Tech startups need to move fast without accumulating technical debt that slows them down later. CiroStack builds scalable MVP architectures, product infrastructure, and engineering foundations that get you to market quickly while remaining extensible as your company grows.",
    "mobile-app-developers": "Mobile app companies need performant, reliable applications that deliver consistent experiences across iOS and Android devices. CiroStack builds custom cross platform architectures, backend API services, push notification systems, and analytics frameworks that accelerate mobile development and improve user retention.",
    "ai-companies": "AI companies need robust infrastructure for training models, managing data pipelines, and deploying predictions at scale. CiroStack builds custom ML operations platforms, data pipeline architectures, model serving infrastructure, and monitoring dashboards that help AI teams iterate faster and deploy confidently.",
    "blockchain-crypto": "Blockchain companies build on rapidly evolving protocols where security vulnerabilities can be catastrophic. CiroStack builds custom smart contract architectures, decentralized application frontends, wallet integrations, and blockchain analytics platforms with institutional grade security baked into every layer.",
    "iot-companies": "IoT companies manage thousands of connected devices generating continuous data streams that must be processed and acted upon reliably. CiroStack builds custom device management platforms, data pipeline architectures, edge computing solutions, and monitoring dashboards that scale with your fleet.",
    "cybersecurity": "Cybersecurity companies protect organizations from evolving threats that demand constant vigilance and rapid response. CiroStack builds custom threat detection platforms, security operations dashboards, compliance automation tools, and incident response systems that help security teams defend against sophisticated attacks.",
    "cloud-services": "Cloud service providers need multi tenant platforms that maintain strict isolation, performance guarantees, and cost efficiency at scale. CiroStack builds custom orchestration layers, resource management dashboards, billing systems, and self service portals that let your customers provision and manage resources.",
    "devops-tools": "DevOps tool companies build products that engineering teams depend on for every deployment and release. CiroStack builds custom CI/CD pipeline integrations, infrastructure monitoring platforms, deployment automation tools, and observability dashboards that help development teams ship reliable software faster.",
    "developer-tools": "Developer tool companies must deliver exceptional developer experiences with clean APIs, thorough documentation, and frictionless onboarding. CiroStack builds custom API platforms, developer portals, SDK generation tools, and usage analytics dashboards that help developer tools achieve adoption and drive engagement.",

    # ===================== AGRICULTURE & FARMING =====================
    "farms": "Modern farms generate vast amounts of data from soil sensors, weather stations, and equipment telemetry that rarely gets used effectively. CiroStack builds custom farm management platforms, crop planning tools, yield analytics dashboards, and equipment integration systems for smarter operations.",
    "agribusiness": "Agribusiness operations span supply chains from seed to sale, requiring coordination across procurement, processing, and distribution. CiroStack builds custom supply chain platforms, crop analytics dashboards, inventory management systems, and logistics tools that help agribusiness operations optimize every stage.",
    "livestock-management": "Livestock operations require precise tracking of animal health, breeding records, feed management, and regulatory compliance across large herds. CiroStack builds custom herd management platforms, health monitoring tools, breeding record systems, and compliance tracking dashboards for efficient livestock operations.",
    "farm-equipment": "Farm equipment dealers and manufacturers manage complex inventory, service scheduling, and parts logistics across wide geographic areas. CiroStack builds custom fleet tracking platforms, maintenance scheduling tools, parts inventory systems, and dealer management portals that keep agricultural equipment running.",
    "produce-distribution": "Produce distributors manage cold chain logistics, freshness tracking, and delivery scheduling for products with extremely short shelf lives. CiroStack builds custom cold chain monitoring platforms, route optimization engines, freshness tracking tools, and order management systems that minimize waste.",
    "organic-farming": "Organic farming operations must maintain meticulous records for certification compliance while managing soil health and sustainable practices. CiroStack builds custom certification tracking platforms, soil management tools, crop rotation planners, and compliance documentation systems that simplify organic operation management.",
    "agricultural-co-ops": "Agricultural cooperatives coordinate purchasing, marketing, and distribution for hundreds of member farmers. CiroStack builds custom member management platforms, collective purchasing tools, crop aggregation systems, and distribution logistics portals that strengthen cooperative efficiency and member profitability.",
    "precision-agriculture": "Precision agriculture uses sensor data, satellite imagery, and machine learning to optimize every acre of production. CiroStack builds custom field mapping platforms, variable rate application tools, sensor integration systems, and yield prediction dashboards that turn agricultural data into actionable insights.",
    "fisheries": "Fisheries manage catch documentation, fleet coordination, regulatory compliance, and market pricing across unpredictable conditions. CiroStack builds custom catch tracking platforms, fleet management tools, compliance reporting systems, and market intelligence dashboards that help fishing operations stay profitable and sustainable.",
    "forestry": "Forestry operations balance harvest planning, environmental compliance, and inventory management across vast land areas. CiroStack builds custom harvest scheduling platforms, timber inventory tools, compliance tracking systems, and environmental monitoring dashboards that optimize sustainable forest resource management.",

    # ===================== CONSTRUCTION & ENGINEERING =====================
    "construction-companies": "Construction companies manage projects where budget overruns and schedule delays can cost millions. CiroStack builds custom project management platforms, budget tracking dashboards, subcontractor coordination tools, and field reporting systems that keep complex construction projects on time and within budget.",
    "architecture-firms-ce": "Architecture firms coordinate design development, client collaboration, and construction documentation across complex building projects. CiroStack builds custom BIM workflow platforms, client review portals, regulatory submission tools, and project management dashboards that streamline the entire architectural design process.",
    "civil-engineering": "Civil engineering projects require precise coordination of design calculations, regulatory approvals, and field inspections across long timelines. CiroStack builds custom project management platforms, inspection tracking tools, compliance documentation systems, and resource planning dashboards that keep infrastructure projects moving forward.",
    "contractors": "General contractors coordinate subcontractors, materials, inspections, and client communications across multiple active job sites simultaneously. CiroStack builds custom job management platforms, scheduling tools, material tracking systems, and client communication portals that keep every project organized and profitable.",
    "subcontractors": "Subcontractors juggle multiple jobs from different general contractors while managing their own crews, materials, and billing. CiroStack builds custom job tracking platforms, crew scheduling tools, material ordering systems, and invoice management portals that maximize productivity across every active project.",
    "building-materials": "Building materials suppliers manage complex inventory, delivery logistics, and contractor relationships across wide service areas. CiroStack builds custom inventory management platforms, delivery scheduling tools, contractor portals, and order tracking systems that ensure the right materials reach job sites on time.",
    "real-estate-development": "Real estate developers coordinate land acquisition, financing, construction, and sales across projects spanning years. CiroStack builds custom development tracking platforms, budget management tools, investor reporting dashboards, and sales management systems that provide visibility across every project phase.",
    "facility-management-ce": "Facility management companies maintain building systems, coordinate service teams, and ensure regulatory compliance across diverse property portfolios. CiroStack builds custom work order platforms, preventive maintenance schedulers, compliance tracking tools, and tenant communication portals that streamline building operations.",
    "renovation-services": "Renovation companies manage design consultations, material selection, subcontractor coordination, and client expectations throughout transformation projects. CiroStack builds custom project management platforms, material tracking tools, client communication portals, and scheduling systems that deliver renovation projects on time and within budget.",
    "landscape-architecture": "Landscape architecture firms design outdoor spaces that balance aesthetics, environmental sustainability, and client vision. CiroStack builds custom project management platforms, design collaboration tools, plant specification databases, and client presentation portals that elevate landscape design workflows and deliverables.",

    # ===================== TRANSPORTATION & LOGISTICS =====================
    "trucking-companies": "Trucking companies manage fleet operations, driver schedules, compliance documentation, and customer shipments across thousands of miles daily. CiroStack builds custom fleet management platforms, dispatch tools, compliance tracking systems, and shipment visibility dashboards that optimize every route and load.",
    "delivery-services": "Delivery services balance speed, accuracy, and cost across constantly changing routes and volumes. CiroStack builds custom dispatch platforms, route optimization engines, real time tracking systems, and proof of delivery tools that help delivery operations scale efficiently while maintaining service quality.",
    "freight-forwarding": "Freight forwarders coordinate shipments across carriers, borders, and transport modes while managing complex documentation and customs requirements. CiroStack builds custom shipment tracking platforms, document management tools, carrier integration systems, and customs compliance portals that simplify global logistics.",
    "warehousing-tl": "Warehousing operations demand precise inventory control, efficient picking workflows, and seamless integration with transportation partners. CiroStack builds custom warehouse management platforms, inventory tracking systems, picking optimization tools, and carrier integration portals that maximize throughput and accuracy.",
    "public-transportation": "Public transit agencies serve millions of riders while managing fleet maintenance, route planning, and budget constraints. CiroStack builds custom passenger information systems, fleet management platforms, route optimization tools, and ridership analytics dashboards that improve service reliability and rider satisfaction.",
    "ride-sharing": "Ride sharing platforms must match drivers with riders instantly while managing pricing, safety, and driver satisfaction. CiroStack builds custom matching algorithms, dynamic pricing engines, driver management platforms, and rider experience tools that create reliable and scalable transportation networks.",
    "courier-services": "Courier services promise fast, reliable delivery of time sensitive packages across congested urban environments. CiroStack builds custom dispatch platforms, route optimization engines, real time tracking tools, and proof of delivery systems that help couriers meet tight deadlines efficiently.",
    "shipping-lines": "Shipping lines manage vessel operations, container tracking, and port logistics across global trade routes. CiroStack builds custom vessel management platforms, container tracking systems, booking portals, and operations dashboards that improve fleet utilization and provide real time cargo visibility.",
    "railway-companies": "Railway companies coordinate train operations, track maintenance, passenger services, and freight logistics across extensive networks. CiroStack builds custom operations management platforms, maintenance scheduling tools, passenger booking systems, and freight tracking dashboards that improve safety and operational efficiency.",
    "aviation": "Aviation companies manage flight operations, crew scheduling, maintenance compliance, and passenger experiences across complex regulatory environments. CiroStack builds custom operations platforms, crew management tools, maintenance tracking systems, and passenger service applications that improve safety and operational performance.",

    # ===================== GOVERNMENT & PUBLIC SECTOR =====================
    "local-government": "Local governments serve residents through permit processing, public records, community services, and infrastructure management. CiroStack builds custom citizen service portals, permit tracking systems, public records platforms, and department workflow tools that modernize municipal operations and improve transparency.",
    "federal-agencies": "Federal agencies manage complex programs, interagency coordination, and public services under strict regulatory and security requirements. CiroStack builds custom program management platforms, secure data systems, compliance automation tools, and citizen service portals that modernize federal operations while meeting FedRAMP standards.",
    "public-safety": "Public safety agencies coordinate emergency response, incident management, and community communication under critical time pressure. CiroStack builds custom dispatch platforms, incident management systems, community alert tools, and data analytics dashboards that help first responders protect communities more effectively.",
    "education-departments": "Education departments oversee curriculum standards, school performance, teacher certification, and student outcomes across entire districts or states. CiroStack builds custom data management platforms, performance tracking dashboards, certification systems, and reporting tools that improve educational oversight and accountability.",
    "health-departments": "Public health departments manage disease surveillance, community wellness programs, and emergency preparedness across diverse populations. CiroStack builds custom epidemiological tracking platforms, community health portals, vaccination management systems, and emergency response dashboards that strengthen public health infrastructure.",
    "transportation-departments": "Transportation departments plan, build, and maintain road networks, bridges, and transit systems serving millions of commuters. CiroStack builds custom asset management platforms, project tracking tools, traffic analytics dashboards, and public information systems that improve infrastructure planning and citizen communication.",
    "parks-and-recreation": "Parks and recreation departments manage facilities, programs, permits, and natural resources that serve entire communities. CiroStack builds custom reservation systems, program registration platforms, facility management tools, and visitor analytics dashboards that help parks departments maximize community engagement and resource efficiency.",
    "libraries": "Modern libraries offer far more than book lending, providing digital resources, community programs, and technology access. CiroStack builds custom catalog management systems, digital resource platforms, program registration tools, and patron engagement dashboards that help libraries serve evolving community needs.",
    "utilities": "Utility companies manage complex infrastructure, billing systems, and customer service across millions of service connections. CiroStack builds custom meter data management platforms, billing systems, outage tracking tools, and customer portals that modernize utility operations and improve service reliability.",
    "tax-authorities": "Tax authorities process millions of returns, manage compliance enforcement, and provide taxpayer services under strict accuracy requirements. CiroStack builds custom return processing platforms, compliance tracking systems, taxpayer portals, and analytics dashboards that improve collection efficiency and reduce processing errors.",

    # ===================== SPORTS & RECREATION =====================
    "sports-teams": "Sports teams manage player performance, fan engagement, ticket sales, and sponsorship relationships across competitive seasons. CiroStack builds custom performance analytics platforms, fan engagement tools, ticketing systems, and sponsorship management dashboards that help teams win both on and off the field.",
    "fitness-centers": "Fitness centers compete on member experience, class variety, and community atmosphere. CiroStack builds custom membership management platforms, class booking systems, trainer scheduling tools, and member engagement dashboards that reduce churn and create fitness communities members genuinely want to belong to.",
    "gyms": "Gyms need technology that keeps members showing up and staying engaged month after month. CiroStack builds custom membership platforms, workout tracking tools, class scheduling systems, and retention analytics dashboards that turn casual visitors into committed long term members.",
    "yoga-studios": "Yoga studios cultivate mindful communities that value personal attention and consistent practice. CiroStack builds custom class booking platforms, membership management tools, instructor scheduling systems, and student progress tracking dashboards that help studios grow while maintaining their intimate community atmosphere.",
    "sports-leagues": "Sports leagues coordinate teams, schedules, officials, and standings across entire seasons while engaging fans and sponsors. CiroStack builds custom league management platforms, scheduling tools, referee assignment systems, and fan engagement portals that keep every season running smoothly.",
    "outdoor-recreation": "Outdoor recreation companies manage equipment rentals, guided experiences, permits, and safety across diverse natural environments. CiroStack builds custom booking platforms, equipment tracking tools, guide scheduling systems, and waiver management portals that help outdoor businesses scale while prioritizing participant safety.",
    "martial-arts-schools": "Martial arts schools balance student progression through belt systems, class scheduling, and community building. CiroStack builds custom student management platforms, belt tracking tools, scheduling systems, and parent communication portals that help schools grow while honoring traditional training values.",
    "dance-studios": "Dance studios manage class schedules, recital planning, student progression, and parent communication across multiple age groups and styles. CiroStack builds custom studio management platforms, scheduling tools, recital coordination systems, and progress tracking portals that keep studios thriving.",
    "golf-courses": "Golf courses manage tee time bookings, membership programs, pro shop inventory, and course maintenance across seasonal demand. CiroStack builds custom tee time reservation platforms, membership management tools, pro shop systems, and operations dashboards that maximize revenue and golfer satisfaction.",
    "sports-events": "Sports event organizers coordinate venues, participants, sponsors, and logistics across competitions that demand precise timing and execution. CiroStack builds custom event management platforms, registration systems, scoring tools, and sponsor engagement dashboards that deliver flawless sporting events at every scale.",

    # ===================== BEAUTY & PERSONAL CARE =====================
    "salons": "Salons depend on repeat clients, full appointment books, and efficient service delivery to stay profitable. CiroStack builds custom booking platforms, client management tools, staff scheduling systems, and loyalty program dashboards that help salons increase retention and maximize daily revenue.",
    "spas": "Spas create wellness experiences that begin the moment a client books an appointment. CiroStack builds custom reservation platforms, treatment management tools, therapist scheduling systems, and guest experience dashboards that help spas deliver seamless relaxation from first booking through final checkout.",
    "barber-shops": "Barber shops thrive on loyal clientele, efficient scheduling, and a strong local reputation. CiroStack builds custom appointment booking platforms, client preference tracking tools, staff scheduling systems, and reputation management dashboards that help barbershops build steady repeat business and community presence.",
    "nail-salons": "Nail salons manage high volume appointments, service customization, and product inventory across busy daily schedules. CiroStack builds custom booking platforms, service tracking tools, inventory management systems, and client communication dashboards that help nail salons serve more clients without sacrificing quality.",
    "estheticians": "Estheticians provide personalized skincare treatments that require detailed client history tracking and careful product recommendations. CiroStack builds custom client management platforms, treatment tracking tools, product recommendation engines, and appointment scheduling systems that help estheticians deliver consistently exceptional results.",
    "tattoo-shops": "Tattoo shops manage custom design consultations, artist schedules, health compliance, and portfolio showcasing. CiroStack builds custom booking platforms, design consultation tools, artist portfolio systems, and health compliance tracking dashboards that help tattoo shops attract clients and streamline creative workflows.",
    "beauty-clinics": "Beauty clinics offer advanced aesthetic treatments requiring precise scheduling, medical compliance, and detailed client records. CiroStack builds custom clinic management platforms, treatment planning tools, compliance tracking systems, and client communication dashboards that help beauty clinics operate safely and scale effectively.",
    "cosmetics-brands": "Cosmetics brands compete on product discovery, shade matching, and personalized recommendations across digital and retail channels. CiroStack builds custom ecommerce platforms, virtual try on tools, shade matching engines, and analytics dashboards that convert browsers into loyal customers.",
    "hair-products": "Hair product companies must educate consumers about ingredients, match products to hair types, and build brand loyalty. CiroStack builds custom ecommerce platforms, hair type assessment tools, subscription management systems, and education portals that help brands grow their customer base.",
    "skincare": "Skincare brands help customers navigate complex routines and ingredient choices for their unique skin concerns. CiroStack builds custom skin assessment tools, product recommendation engines, subscription platforms, and educational content systems that build trust and drive informed purchasing.",

    # ===================== AUTOMOTIVE =====================
    "car-dealerships": "Car dealerships manage inventory, financing, trade ins, and customer relationships across sales floors and service departments. CiroStack builds custom dealer management platforms, inventory tracking tools, financing workflow systems, and customer relationship portals that accelerate sales and improve service retention.",
    "auto-repair-shops": "Auto repair shops juggle diagnostic workflows, parts ordering, customer approvals, and technician scheduling across dozens of vehicles daily. CiroStack builds custom shop management platforms, digital inspection tools, parts ordering systems, and communication portals that increase throughput and trust.",
    "car-washes": "Car wash operations manage high volume vehicle throughput, membership programs, and equipment maintenance across busy locations. CiroStack builds custom point of sale systems, membership management platforms, equipment monitoring tools, and loyalty dashboards that maximize wash volume and recurring revenue.",
    "auto-parts-stores": "Auto parts stores manage vast inventories with complex fitment data across thousands of vehicle applications. CiroStack builds custom catalog management platforms, fitment verification tools, inventory systems, and ecommerce portals that help parts stores deliver accurate results and reduce costly returns.",
    "fleet-management": "Fleet managers oversee vehicle maintenance, driver compliance, fuel costs, and route efficiency across entire vehicle fleets. CiroStack builds custom fleet tracking platforms, maintenance scheduling tools, driver compliance systems, and cost analytics dashboards that reduce operating expenses and extend fleet lifespan.",
    "rental-cars": "Rental car companies balance fleet availability, pricing strategy, vehicle maintenance, and customer service across multiple locations. CiroStack builds custom fleet management platforms, dynamic pricing tools, reservation systems, and vehicle tracking dashboards that maximize utilization rates and revenue per vehicle.",
    "motorcycle-shops": "Motorcycle shops serve passionate enthusiasts who value expertise, customization, and community. CiroStack builds custom inventory management platforms, service scheduling tools, parts ordering systems, and customer community portals that help motorcycle shops build loyalty and grow sales across bikes and accessories.",
    "tire-shops": "Tire shops manage seasonal demand fluctuations, vehicle fitment data, and service scheduling across busy retail operations. CiroStack builds custom appointment booking platforms, tire fitment tools, inventory management systems, and communication dashboards that keep bays full and customers informed.",
    "body-shops": "Body shops coordinate insurance claims, repair estimates, parts sourcing, and customer communication across complex repair workflows. CiroStack builds custom repair management platforms, estimate tools, insurance integration systems, and customer status portals that streamline collision repair from intake through final delivery.",
    "automotive-detailing": "Automotive detailing businesses manage appointment scheduling, service packages, product inventory, and customer relationships across mobile and fixed locations. CiroStack builds custom booking platforms, service management tools, inventory tracking systems, and customer loyalty dashboards that help detailing businesses grow efficiently.",

    # ===================== LEGAL SERVICES =====================
    "law-firms-legal": "Law firms manage complex caseloads, client relationships, and billing across practice areas that each demand specialized workflows. CiroStack builds custom case management platforms, document automation tools, time tracking systems, and client portals that let attorneys focus on practicing law.",
    "solo-practitioners": "Solo practitioners handle every aspect of their practice from client intake through case resolution without support staff. CiroStack builds custom practice management platforms, document assembly tools, client portals, and billing systems that give solo attorneys the efficiency of larger firms.",
    "corporate-law": "Corporate law practices manage transactions, compliance reviews, and due diligence across deals involving massive document volumes. CiroStack builds custom deal room platforms, document review tools, compliance tracking systems, and collaboration portals that accelerate transactions while reducing oversight risk.",
    "family-law": "Family law practices handle emotionally sensitive cases requiring careful client communication, court deadline management, and complex financial calculations. CiroStack builds custom case management platforms, communication portals, deadline tracking tools, and financial calculation systems that bring order to workflows.",
    "criminal-defense": "Criminal defense attorneys work under strict deadlines with extensive discovery materials and complex procedural requirements. CiroStack builds custom case management platforms, discovery review tools, deadline tracking systems, and client communication portals that help defense attorneys build stronger cases.",
    "immigration-law": "Immigration law firms manage cases across constantly changing regulations, multiple government agencies, and lengthy processing timelines. CiroStack builds custom case tracking platforms, form automation tools, deadline management systems, and client portals that help attorneys navigate complex regulatory landscapes.",
    "intellectual-property": "Intellectual property firms manage patent portfolios, trademark filings, and licensing agreements across complex prosecution and litigation matters. CiroStack builds custom portfolio management platforms, filing deadline trackers, prior art research tools, and reporting dashboards that protect and monetize intellectual assets.",
    "real-estate-law": "Real estate law practices coordinate closings, title searches, and contract reviews across transactions involving multiple parties and strict deadlines. CiroStack builds custom transaction management platforms, document automation tools, closing coordination systems, and portals that streamline every matter.",
    "estate-planning": "Estate planning attorneys help clients protect wealth and wishes through wills, trusts, and succession plans that must be precise. CiroStack builds custom estate planning platforms, document automation tools, client review portals, and update tracking systems that simplify complex planning workflows.",
    "legal-aid": "Legal aid organizations serve communities with limited resources, handling high caseloads across diverse practice areas simultaneously. CiroStack builds custom intake management platforms, case tracking tools, volunteer coordination systems, and impact reporting dashboards that help organizations serve more people.",

    # ===================== SMALL BUSINESS =====================
    "local-retail": "Local retailers compete against national chains and online marketplaces with personalized service and community presence. CiroStack builds custom point of sale platforms, inventory management tools, customer loyalty systems, and local marketing dashboards that help independent retailers thrive in competitive markets.",
    "restaurants-sb": "Small restaurants manage orders, kitchen operations, and customer loyalty while keeping food costs under control across tight margins. CiroStack builds custom POS integrations, online ordering platforms, inventory tracking tools, and customer engagement systems that help independent restaurants operate profitably.",
    "salons-sb": "Small salon owners handle appointments, staff scheduling, product inventory, and client relationships while managing every aspect of their business. CiroStack builds custom booking platforms, staff management tools, inventory systems, and client dashboards that let owners focus on their craft.",
    "gyms-sb": "Small gym owners build fitness communities while managing memberships, class schedules, and facility maintenance on limited budgets. CiroStack builds custom membership platforms, class booking tools, payment systems, and engagement dashboards that help independent gyms compete with national franchise chains.",
    "law-firms-sb": "Small law firms balance legal expertise with the business demands of running a practice. CiroStack builds custom practice management platforms, client intake tools, billing systems, and document portals that give small firms the efficiency of larger practices without enterprise overhead.",
    "accounting-firms-sb": "Small accounting firms serve clients across tax preparation, bookkeeping, and advisory services with limited staff. CiroStack builds custom client management platforms, tax workflow tools, document collection systems, and billing dashboards that help small firms handle more clients with greater efficiency.",
    "real-estate-agents-sb": "Independent real estate agents manage listings, client relationships, and transaction paperwork while competing against large brokerages. CiroStack builds custom CRM platforms, listing management tools, transaction tracking systems, and marketing automation dashboards that level the competitive playing field for independent agents.",
    "consultants": "Independent consultants deliver expert advice while managing client acquisition, project delivery, and invoicing on their own. CiroStack builds custom client management platforms, proposal tools, project tracking systems, and billing dashboards that help consultants operate with the polish of established firms.",
    "contractors-sb": "Small contractors estimate jobs, coordinate crews, manage materials, and handle client communications across multiple active projects simultaneously. CiroStack builds custom job management platforms, estimating tools, crew scheduling systems, and client communication portals that help contractors stay organized and grow profitably.",
    "freelancers": "Freelancers manage client acquisition, project delivery, invoicing, and professional development while building sustainable independent careers. CiroStack builds custom portfolio platforms, project management tools, invoicing systems, and client communication dashboards that help freelancers present professionally and operate efficiently at scale.",
}

# Read the file
with open('src/data/industries-generated.ts', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Parse to find description lines
current_slug = None
current_title = None
edits = []

for i, line in enumerate(lines):
    m = re.match(r'\s+"([a-z0-9-]+)":\s*\{', line)
    if m:
        current_slug = m.group(1)
        current_title = None
    m2 = re.match(r'\s+title:\s*"(.+?)"', line)
    if m2 and current_slug:
        current_title = m2.group(1)
    m3 = re.match(r'^(        description:\s*")(.+)(",?\s*)$', line)
    if m3 and current_slug and current_title:
        if current_slug in NEW_DESCRIPTIONS:
            new_desc = NEW_DESCRIPTIONS[current_slug]
            edits.append({
                'line': i,
                'slug': current_slug,
                'prefix': m3.group(1),
                'suffix': m3.group(3),
                'new_desc': new_desc
            })
        current_slug = None

# Validate all descriptions
errors = []
for slug, desc in NEW_DESCRIPTIONS.items():
    wc = len(desc.split())
    if wc < 35 or wc > 40:
        errors.append(f"  {slug}: {wc} words")
    if '-' in desc:
        errors.append(f"  {slug}: contains dash(es)")

if errors:
    print("VALIDATION ERRORS:")
    for e in errors:
        print(e)
    print(f"\nTotal errors: {len(errors)}")
    print("Fix these before applying!")
else:
    print(f"All {len(NEW_DESCRIPTIONS)} descriptions validated (35-40 words, no dashes)")

# Check coverage
found_slugs = set(e['slug'] for e in edits)
missing = set(NEW_DESCRIPTIONS.keys()) - found_slugs
if missing:
    print(f"\nWARNING: {len(missing)} slugs not found in file: {missing}")

not_covered = []
for i, line in enumerate(lines):
    m = re.match(r'^(        description:\s*")(.+)(",?\s*)$', line)
    if m:
        # Check if this line is being edited
        if not any(e['line'] == i for e in edits):
            not_covered.append(i+1)

if not_covered:
    print(f"\nNOTE: {len(not_covered)} description lines not covered (nested descriptions in solutions/services)")

print(f"\nTotal edits to apply: {len(edits)}")
print(f"Total descriptions defined: {len(NEW_DESCRIPTIONS)}")

# Apply edits
if not errors:
    for edit in edits:
        lines[edit['line']] = edit['prefix'] + edit['new_desc'] + edit['suffix']

    with open('src/data/industries-generated.ts', 'w', encoding='utf-8') as f:
        f.writelines(lines)

    print("\nAll edits applied successfully!")
